ALTER TABLE appointments_temp
ADD COLUMN IF NOT EXISTS estimated_arrival_time TIMESTAMP,
ADD COLUMN IF NOT EXISTS actual_arrival_time TIMESTAMP,
ADD COLUMN IF NOT EXISTS predicted_duration_minutes INTEGER DEFAULT 30,
ADD COLUMN IF NOT EXISTS assigned_dock VARCHAR(50),
ADD COLUMN IF NOT EXISTS sla_minutes INTEGER DEFAULT 120,
ADD COLUMN IF NOT EXISTS detention_cost_per_hour NUMERIC(10,2) DEFAULT 100.00;