"""Create normalized warehouse schema

Revision ID: 1e785c75eaad
Revises: a9000e8afc52
Create Date: 2026-07-22 15:31:45.659725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e785c75eaad'
down_revision: Union[str, Sequence[str], None] = 'a9000e8afc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "facilities",
        sa.Column(
            "facility_id",
            sa.String(length=100),
            primary_key=True,
        ),
        sa.Column(
            "facility_name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "timezone",
            sa.String(length=50),
            nullable=False,
            server_default="America/New_York",
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    op.create_table(
        "carriers",
        sa.Column(
            "carrier_id",
            sa.String(length=100),
            primary_key=True,
        ),
        sa.Column(
            "carrier_name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    op.create_table(
        "docks",
        sa.Column(
            "dock_id",
            sa.String(length=50),
            primary_key=True,
        ),
        sa.Column(
            "facility_id",
            sa.String(length=100),
            sa.ForeignKey("facilities.facility_id"),
            nullable=False,
        ),
        sa.Column(
            "dock_name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "dock_type",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "temperature_zone",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    op.create_table(
        "appointments",
        sa.Column(
            "appt_id",
            sa.String(length=50),
            primary_key=True,
        ),
        sa.Column(
            "appt_date",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "customer_id",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "customer_name",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "facility_id",
            sa.String(length=100),
            sa.ForeignKey("facilities.facility_id"),
            nullable=False,
        ),
        sa.Column(
            "carrier_id",
            sa.String(length=100),
            sa.ForeignKey("carriers.carrier_id"),
            nullable=True,
        ),
        sa.Column(
            "scheduled_time",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "estimated_arrival_time",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "actual_arrival_time",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "planned_start_time",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "actual_start_time",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "planned_end_time",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "actual_end_time",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "assigned_dock_id",
            sa.String(length=50),
            sa.ForeignKey("docks.dock_id"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False,
            server_default="Scheduled",
        ),
        sa.Column(
            "appointment_type",
            sa.String(length=30),
            nullable=True,
        ),
        sa.Column(
            "load_type",
            sa.String(length=30),
            nullable=True,
        ),
        sa.Column(
            "trailer_number",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "pallet_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "sku_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "total_weight",
            sa.Numeric(12, 2),
            nullable=True,
        ),
        sa.Column(
            "total_cube",
            sa.Numeric(12, 2),
            nullable=True,
        ),
        sa.Column(
            "priority",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
        sa.Column(
            "sla_minutes",
            sa.Integer(),
            nullable=False,
            server_default="120",
        ),
        sa.Column(
            "detention_cost_per_hour",
            sa.Numeric(10, 2),
            nullable=False,
            server_default="100.00",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.create_table(
        "appointment_events",
        sa.Column(
            "event_id",
            sa.BigInteger(),
            primary_key=True,
            autoincrement=True,
        ),
        sa.Column(
            "appt_id",
            sa.String(length=50),
            sa.ForeignKey(
                "appointments.appt_id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "event_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "event_time",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.create_table(
        "appointment_predictions",
        sa.Column(
            "prediction_id",
            sa.BigInteger(),
            primary_key=True,
            autoincrement=True,
        ),
        sa.Column(
            "appt_id",
            sa.String(length=50),
            sa.ForeignKey(
                "appointments.appt_id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "predicted_arrival_time",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "predicted_delay_minutes",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "predicted_duration_minutes",
            sa.Integer(),
            nullable=False,
            server_default="30",
        ),
        sa.Column(
            "sla_miss_probability",
            sa.Numeric(5, 4),
            nullable=True,
        ),
        sa.Column(
            "sla_recovery_probability",
            sa.Numeric(5, 4),
            nullable=True,
        ),
        sa.Column(
            "turn_risk_score",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "predicted_missed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "model_version",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.create_table(
        "appointment_recommendations",
        sa.Column(
            "recommendation_id",
            sa.BigInteger(),
            primary_key=True,
            autoincrement=True,
        ),
        sa.Column(
            "appt_id",
            sa.String(length=50),
            sa.ForeignKey(
                "appointments.appt_id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "recommendation_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "recommended_action",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "recommended_dock_id",
            sa.String(length=50),
            sa.ForeignKey("docks.dock_id"),
            nullable=True,
        ),
        sa.Column(
            "recommended_sequence",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "additional_labor",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "estimated_loss_without_action",
            sa.Numeric(12, 2),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "estimated_cost_of_action",
            sa.Numeric(12, 2),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "estimated_savings",
            sa.Numeric(12, 2),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False,
            server_default="Pending",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "responded_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "responded_by",
            sa.String(length=100),
            nullable=True,
        ),
    )

    op.create_index(
        "ix_appointments_scheduled_time",
        "appointments",
        ["scheduled_time"],
    )

    op.create_index(
        "ix_appointments_status",
        "appointments",
        ["status"],
    )

    op.create_index(
        "ix_appointment_events_appt_id",
        "appointment_events",
        ["appt_id"],
    )

    op.create_index(
        "ix_appointment_predictions_appt_id",
        "appointment_predictions",
        ["appt_id"],
    )

    op.create_index(
        "ix_appointment_recommendations_appt_id",
        "appointment_recommendations",
        ["appt_id"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_appointment_recommendations_appt_id",
        table_name="appointment_recommendations",
    )
    op.drop_index(
        "ix_appointment_predictions_appt_id",
        table_name="appointment_predictions",
    )
    op.drop_index(
        "ix_appointment_events_appt_id",
        table_name="appointment_events",
    )
    op.drop_index(
        "ix_appointments_status",
        table_name="appointments",
    )
    op.drop_index(
        "ix_appointments_scheduled_time",
        table_name="appointments",
    )

    op.drop_table("appointment_recommendations")
    op.drop_table("appointment_predictions")
    op.drop_table("appointment_events")
    op.drop_table("appointments")
    op.drop_table("docks")
    op.drop_table("carriers")
    op.drop_table("facilities")